# Site settings
title: "The Subie Doctor"
email: "team@variantstudios.com"
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/ - keep empty!
url: "https://thesubiedoctor.com" # the base hostname & protocol for your site - don't include the forward slash
#timezone: America/Denver - Don't set for CloudCannon...for reasons.
version: "3.2.1" # the version of jekyll

#CloudCannon defaults
uploads_dir: "assets/images"

# Gems for plugins
gems:
  - jekyll-paginate-v2 # Needed to add paginate on Jekyll ver 3+
  - jekyll-sitemap # Simple jekyll plugin that creates a sitemap.xml file and you can exclude files by adding 'sitemap:false' to the frontmatter of any file(s).

# Permalinks
permalink: pretty

# Pagination V2 Settings: https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: false
  per_page: 2
  permalink: '/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'title'
  sort_reverse: false
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true
  # The default document collection to paginate if nothing is specified ('posts' is default)
  #collection: 'posts'

#Collections
collections:
  sg:
    output: false
  cars:
    output: true
    permalink: '/car-inventory/:title/'
  

# Collection Defaults
defaults:
  -
    scope:
      type: sg
    values:
      layout: styleguide-block
  -
    scope:
      type: cars
    values:
      layout: car

# Default Select Options (client can't change)
car_category_options:
  - new
  - used
inventory_options:
  - coming
  - for_sale
  - sold


# Cloudinary URL - something like: https://res.cloudinary.com/domain-com/
cloudinaryurl: "https://res.cloudinary.com/thesubiedoctor/"

# typekit - Because we all need nice type faces. --- afz7owd
typekit: "afz7owd"

# Google Analytics - What site isn't using it?! --- UA-97408360-1
google_analytics_tracking_id: "UA-97408360-1"

exclude: ["readme.md", "vendor","node_modules","package.json", "package-lock.json","Gemfile","gulpfile.js","*.scss"]